// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeo5Uau6H4F3wGLFzC4GMNfM86Uys_-zs',
    appId: '1:894508282649:web:bdf2dd3b19e0fdc15d0b88',
    messagingSenderId: '894508282649',
    projectId: 'systempos-86ada',
    authDomain: 'systempos-86ada.firebaseapp.com',
    storageBucket: 'systempos-86ada.firebasestorage.app',
    measurementId: 'G-2065PE7PWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAI-yQO6O2ydhNbFVltKCvf5yZ2NoBU9U',
    appId: '1:894508282649:android:e54c774834627ff65d0b88',
    messagingSenderId: '894508282649',
    projectId: 'systempos-86ada',
    storageBucket: 'systempos-86ada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aw8oedpRmQDWNrx06sBQ48qbYvrEuCc',
    appId: '1:894508282649:ios:37be7d2809ac83175d0b88',
    messagingSenderId: '894508282649',
    projectId: 'systempos-86ada',
    storageBucket: 'systempos-86ada.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7aw8oedpRmQDWNrx06sBQ48qbYvrEuCc',
    appId: '1:894508282649:ios:37be7d2809ac83175d0b88',
    messagingSenderId: '894508282649',
    projectId: 'systempos-86ada',
    storageBucket: 'systempos-86ada.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeo5Uau6H4F3wGLFzC4GMNfM86Uys_-zs',
    appId: '1:894508282649:web:390180ecaec3bd825d0b88',
    messagingSenderId: '894508282649',
    projectId: 'systempos-86ada',
    authDomain: 'systempos-86ada.firebaseapp.com',
    storageBucket: 'systempos-86ada.firebasestorage.app',
    measurementId: 'G-9THE8X24C9',
  );
}
