import 'package:cloud_firestore/cloud_firestore.dart';

class InventarioSeeder {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Método para insertar en lotes (más eficiente)
  Future<void> insertarInventarioEnLotes() async {
    try {
      print('Iniciando inserción de inventario en lotes...');

      final productos = _obtenerProductos();

      // Firebase permite máximo 500 operaciones por lote
      const tamanioLote = 500;

      for (int i = 0; i < productos.length; i += tamanioLote) {
        final batch = _firestore.batch();
        final finLote = (i + tamanioLote < productos.length)
            ? i + tamanioLote
            : productos.length;

        for (int j = i; j < finLote; j++) {
          final producto = productos[j];
          final docRef = _firestore
              .collection('inventario')
              .doc(producto['id']);
          batch.set(docRef, producto);
        }

        await batch.commit();
        print(
          'Lote ${(i / tamanioLote).floor() + 1} completado: $finLote productos',
        );
      }

      print(
        '✅ Inventario insertado exitosamente: ${productos.length} productos',
      );
    } catch (e) {
      print('❌ Error al insertar inventario: $e');
      rethrow;
    }
  }

  // Método para verificar si ya existen datos
  Future<bool> inventarioYaExiste() async {
    final snapshot = await _firestore.collection('inventario').limit(1).get();
    return snapshot.docs.isNotEmpty;
  }

  // AQUÍ PEGAS LA LISTA DE PRODUCTOS
  // Reemplaza todo desde "List<Map<String, dynamic>> _obtenerProductos() {"
  // hasta el final del método con el cierre de llaves }
  List<Map<String, dynamic>> _obtenerProductos() {
    return [
      {
        "id": "PAR-0001",
        "nombre": "Jitomate",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0002",
        "nombre": "Tomate",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0003",
        "nombre": "Chile Jalapeño",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Salsas",
      },
      {
        "id": "PAR-0004",
        "nombre": "Chile Serrano",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Salsas",
      },
      {
        "id": "PAR-0005",
        "nombre": "Papas PARA HERVIR",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Guarniciones",
      },
      {
        "id": "PAR-0006",
        "nombre": "Cilantro",
        "categoria": "cocina",
        "unidad_medida": "manojo",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0007",
        "nombre": "Lechuga Italiana",
        "categoria": "cocina",
        "unidad_medida": "pieza",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Ensaladas",
      },
      {
        "id": "PAR-0008",
        "nombre": "Epazote",
        "categoria": "cocina",
        "unidad_medida": "manojo",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0009",
        "nombre": "Rabano",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Guarniciones",
      },
      {
        "id": "PAR-0010",
        "nombre": "Pimiento",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0011",
        "nombre": "Cebolla",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0012",
        "nombre": "Manzana",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Jugos/Postres",
      },
      {
        "id": "PAR-0013",
        "nombre": "Fresa",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Jugos/Postres",
      },
      {
        "id": "PAR-0014",
        "nombre": "Platano Macho",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0015",
        "nombre": "Limon",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0016",
        "nombre": "Naranja",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Jugos",
      },
      {
        "id": "PAR-0017",
        "nombre": "Toronja",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Jugos",
      },
      {
        "id": "PAR-0018",
        "nombre": "Norsuiza",
        "categoria": "cocina",
        "unidad_medida": "pza",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Condimentos",
      },
      {
        "id": "PAR-0019",
        "nombre": "Sal",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Condimentos",
      },
      {
        "id": "PAR-0020",
        "nombre": "Piña",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Jugos/Postres",
      },
      {
        "id": "PAR-0021",
        "nombre": "Aguacate",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0022",
        "nombre": "Miel",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina/Postres",
      },
      {
        "id": "PAR-0023",
        "nombre": "Nopal",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0024",
        "nombre": "Queso Oaxaca",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0025",
        "nombre": "Queso Enchilado",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0026",
        "nombre": "Queso Rayado",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0027",
        "nombre": "Jamaica",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0028",
        "nombre": "Nuez Granillo",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Postres",
      },
      {
        "id": "PAR-0029",
        "nombre": "Clavo de Olor",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Especias",
      },
      {
        "id": "PAR-0030",
        "nombre": "Comino",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Especias",
      },
      {
        "id": "PAR-0031",
        "nombre": "Pimienta",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Especias",
      },
      {
        "id": "PAR-0032",
        "nombre": "Chile Guajillo",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Salsas",
      },
      {
        "id": "PAR-0033",
        "nombre": "Chile Morita",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Salsas",
      },
      {
        "id": "PAR-0034",
        "nombre": "Chile Ancho",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Salsas",
      },
      {
        "id": "PAR-0035",
        "nombre": "Romero",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Especias",
      },
      {
        "id": "PAR-0036",
        "nombre": "Menta o Hierbabuena",
        "categoria": "cocina",
        "unidad_medida": "manojo",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0037",
        "nombre": "Queso Panela",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0038",
        "nombre": "PAPEL HIGIENICO",
        "categoria": "limpieza",
        "unidad_medida": "pza",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Baños",
      },
      {
        "id": "PAR-0039",
        "nombre": "GRANADINA",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0040",
        "nombre": "JARABE NATURAL",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0041",
        "nombre": "CROTONES",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Ensaladas",
      },
      {
        "id": "PAR-0042",
        "nombre": "DETERGENTE LIQUIDO",
        "categoria": "limpieza",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Limpieza",
      },
      {
        "id": "PAR-0043",
        "nombre": "JABON LIQUIDO DE BAÑO",
        "categoria": "limpieza",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Baños",
      },
      {
        "id": "PAR-0044",
        "nombre": "AJO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0045",
        "nombre": "MAGGY",
        "categoria": "cocina",
        "unidad_medida": "pza",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0046",
        "nombre": "SALSA INGLESA",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0047",
        "nombre": "CHAMPIÑON",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0048",
        "nombre": "CLAMATO",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0049",
        "nombre": "TOALLAS PARA BAÑO",
        "categoria": "limpieza",
        "unidad_medida": "pza",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Baños",
      },
      {
        "id": "PAR-0050",
        "nombre": "CARNE PARA HAMBURGUESA",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0051",
        "nombre": "BOLSA PARA BASURA",
        "categoria": "limpieza",
        "unidad_medida": "pza",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Limpieza",
      },
      {
        "id": "PAR-0052",
        "nombre": "PEPINILLOS",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0053",
        "nombre": "ADEREZO DE MOSTAZA CON MIEL",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0054",
        "nombre": "ADEREZO RANCH",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0055",
        "nombre": "JUGO DE PIÑA",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0056",
        "nombre": "CALAHUA",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0057",
        "nombre": "CREMA",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0058",
        "nombre": "SOBRES DE MOSTAZA",
        "categoria": "cocina",
        "unidad_medida": "pza",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Servicio",
      },
      {
        "id": "PAR-0059",
        "nombre": "VINO DON SIMON",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0060",
        "nombre": "CONDIMENTO ESTILO ITALIANO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Especias",
      },
      {
        "id": "PAR-0061",
        "nombre": "QUESO PARMESANO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0062",
        "nombre": "HELADO DE VAINILLA",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Postres",
      },
      {
        "id": "PAR-0063",
        "nombre": "GRANOS DE CAFE",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0064",
        "nombre": "ACEITE DE OLIVA",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0065",
        "nombre": "LECHERA",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Postres",
      },
      {
        "id": "PAR-0066",
        "nombre": "FRUTOS ROJOS",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Postres/Jugos",
      },
      {
        "id": "PAR-0067",
        "nombre": "DETERGENTE EN POLVO",
        "categoria": "limpieza",
        "unidad_medida": "kg",
        "proveedor": "SAMS",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Limpieza",
      },

      {
        "id": "PAR-0068",
        "nombre": "ACEITE",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0069",
        "nombre": "TOCINO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0070",
        "nombre": "SIRLOIN",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Parrilla",
      },
      {
        "id": "PAR-0071",
        "nombre": "MILANESA DE CERDO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0072",
        "nombre": "MILANESA DE POLLO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0073",
        "nombre": "PAPAS A LA FRANCESA",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Guarniciones",
      },
      {
        "id": "PAR-0074",
        "nombre": "NUGGETS",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0075",
        "nombre": "T-BONE",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Parrilla",
      },
      {
        "id": "PAR-0076",
        "nombre": "RIB EYE",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Parrilla",
      },
      {
        "id": "PAR-0077",
        "nombre": "COSTILLA DE CERDO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Parrilla",
      },
      {
        "id": "PAR-0078",
        "nombre": "SALSA BBQ",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Salsas",
      },
      {
        "id": "PAR-0079",
        "nombre": "CHAMORRO DE CERDO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0080",
        "nombre": "SALSA BBQ PICANTE",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Salsas",
      },
      {
        "id": "PAR-0081",
        "nombre": "SLASA MANGO HABANERO",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Salsas",
      },
      {
        "id": "PAR-0082",
        "nombre": "KETCHUP",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Salsas",
      },
      {
        "id": "PAR-0083",
        "nombre": "MAYONESA",
        "categoria": "cocina",
        "unidad_medida": "lt",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0084",
        "nombre": "JAMON",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0085",
        "nombre": "QUESO MOZZARELA",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0086",
        "nombre": "QUESO GOUDA",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0087",
        "nombre": "SOBRES DE KETCHUP",
        "categoria": "cocina",
        "unidad_medida": "pza",
        "proveedor": "Carnemart",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Servicio",
      },
      {
        "id": "PAR-0088",
        "nombre": "FRIJOL CRUDO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0089",
        "nombre": "FRIJOL DE BOLSA",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0090",
        "nombre": "SERVILLETA PARA TENEDOR",
        "categoria": "limpieza",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Servicio",
      },
      {
        "id": "PAR-0091",
        "nombre": "SERVILLETA PARA MESA",
        "categoria": "limpieza",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Servicio",
      },
      {
        "id": "PAR-0092",
        "nombre": "SERVITOALLAS",
        "categoria": "limpieza",
        "unidad_medida": "rollo",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Servicio",
      },
      {
        "id": "PAR-0093",
        "nombre": "ARROZ",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0094",
        "nombre": "TORTILLA BURRERA",
        "categoria": "cocina",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0095",
        "nombre": "SPAGHETTI",
        "categoria": "cocina",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0096",
        "nombre": "TORTILLINAS",
        "categoria": "cocina",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0097",
        "nombre": "PLASTICO ADHERENTE",
        "categoria": "desechables",
        "unidad_medida": "rollo",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Empaque",
      },
      {
        "id": "PAR-0098",
        "nombre": "TENEDOR GRANDE",
        "categoria": "desechables",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Servicio",
      },
      {
        "id": "PAR-0099",
        "nombre": "VASO DE 1 LITRO CON TAPA",
        "categoria": "desechables",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0100",
        "nombre": "VASO #8 CON TAPA",
        "categoria": "desechables",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0101",
        "nombre": "CONTENEDOR 7x7",
        "categoria": "desechables",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Empaque",
      },
      {
        "id": "PAR-0102",
        "nombre": "PLATO HAMBURGUESERO",
        "categoria": "desechables",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Servicio",
      },
      {
        "id": "PAR-0103",
        "nombre": "CONTENEDOR PARA ENSALADA",
        "categoria": "desechables",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Empaque",
      },
      {
        "id": "PAR-0104",
        "nombre": "AZUCAR",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina/Postres",
      },
      {
        "id": "PAR-0105",
        "nombre": "ATUN",
        "categoria": "cocina",
        "unidad_medida": "lata",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0106",
        "nombre": "BIMBOLLOS",
        "categoria": "cocina",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0107",
        "nombre": "OBLEAS",
        "categoria": "cocina",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Postres",
      },
      {
        "id": "PAR-0108",
        "nombre": "CAFE SOLUBLE",
        "categoria": "cocina",
        "unidad_medida": "frasco",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas",
      },
      {
        "id": "PAR-0109",
        "nombre": "ALUMINIO GRUESO",
        "categoria": "desechables",
        "unidad_medida": "rollo",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Empaque",
      },
      {
        "id": "PAR-0110",
        "nombre": "ALUMINIO DELGADO",
        "categoria": "desechables",
        "unidad_medida": "rollo",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Empaque",
      },
      {
        "id": "PAR-0111",
        "nombre": "BOLSA DE ASA CH",
        "categoria": "desechables",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Empaque",
      },
      {
        "id": "PAR-0112",
        "nombre": "BOLSA DE ASA MEDIANA",
        "categoria": "desechables",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Empaque",
      },
      {
        "id": "PAR-0113",
        "nombre": "BOLSA DE ASA GRANDE",
        "categoria": "desechables",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Empaque",
      },
      {
        "id": "PAR-0114",
        "nombre": "CARBON",
        "categoria": "otros",
        "unidad_medida": "kg",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Parrilla",
      },
      {
        "id": "PAR-0115",
        "nombre": "TORTILLAS PARA TOTOPO",
        "categoria": "cocina",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0116",
        "nombre": "BOLILLOS",
        "categoria": "cocina",
        "unidad_medida": "paquete",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0117",
        "nombre": "MOLE ROJO",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0118",
        "nombre": "CHILES EN VINAGRE",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Servicio",
      },
      {
        "id": "PAR-0119",
        "nombre": "CHAROLAS PARA PARRILLADA",
        "categoria": "otros",
        "unidad_medida": "pza",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Equipo",
      },
      {
        "id": "PAR-0120",
        "nombre": "ROLLO DE SERVITOALLAS",
        "categoria": "desechables",
        "unidad_medida": "rollo",
        "proveedor": "Varios",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Servicio",
      },

      {
        "id": "PAR-0121",
        "nombre": "Lechuga Orejona",
        "categoria": "cocina",
        "unidad_medida": "pieza",
        "proveedor": "mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Ensaladas",
      },
      {
        "id": "PAR-0122",
        "nombre": "Miguelito",
        "categoria": "cocina",
        "unidad_medida": "frasco",
        "proveedor": "mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas / Botanas",
      },
      {
        "id": "PAR-0123",
        "nombre": "Chamoy",
        "categoria": "cocina",
        "unidad_medida": "botella",
        "proveedor": "mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Bebidas / Botanas",
      },
      {
        "id": "PAR-0124",
        "nombre": "Canela en Polvo",
        "categoria": "cocina",
        "unidad_medida": "frasco",
        "proveedor": "mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Postres / Bebidas",
      },
      {
        "id": "PAR-0125",
        "nombre": "Longaniza",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0126",
        "nombre": "Tuétanos",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Cocina",
      },
      {
        "id": "PAR-0127",
        "nombre": "Ajonjolí",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "mercado",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Decoración / Cocina",
      },
      {
        "id": "PAR-0127",
        "nombre": "Huevo",
        "categoria": "cocina",
        "unidad_medida": "kg",
        "proveedor": "otros",
        "fecha_compra": "2025-01-01",
        "precio_unitario": 0.0,
        "stock": 0,
        "stock_minimo": 0,
        "uso_principal": "Decoración / Cocina",
      },
    ];
  }
}
